---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/christian-toledo/christian-concourse.git
    branch: master
jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
  - task: hello-world
    file: resource-tutorial/task_hello_world.yml
